export const AUTH_USER = 'auth_user',
    UNAUTH_USER = 'unauth_user',
    AUTH_ERROR = 'auth_error',
    REGISTER_SUCCESS = 'register_success',
    REGISTER_FAIL = 'register_failed',
    ADD_SUCCESS = 'register_success',
    ADD_FAIL = 'register_failed',
    FORGOT_PASSWORD_REQUEST = 'forgot_password_request',
    RESET_PASSWORD_REQUEST = 'reset_password_request';